### ISSUE TITLE
Dynamic Paramater

### ISSUE THREAD

**Issue by rkesize** [marutim/vc-add-shortcodes#1]
Hi,

thank you for the great Plugin.

It is possible to add dynamic parameters. For example a dropdown with all post id´s?

Or it is possible to add a Shortcode in the Parameter options too?

**Comment by marutim** [comment]
Hi @rkesize 

Thanks for the appreciation.

This is just an example on how to create custom elements/components for visual composer. You can read more about this here http://www.sourcexpress.com/add-custom-shortcodes-visual-composer-plugin/

Thanks
